# @package _group_

porseman_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.porseman_wiki
  id_prefix: ''

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'
