# @package _group_

porseman_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.porseman_wiki
  id_prefix: ''

porseman2_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.porseman2_wiki
  id_prefix: ''

msmarco_super_small:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.msmarco_super_small
  id_prefix: ''

binary_msmarco_super_small:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.binary_msmarco_super_small
  id_prefix: ''

c50_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.c50_wiki
  id_prefix: ''