# @package _group_

porseman_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.porseman-train

porseman_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.porseman-dev

porseman_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.porseman-test

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test
  
curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test
