# @package _group_

# porseman 1 (mozafari)
porseman_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman-train

porseman_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman-dev

porseman_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.porseman-test

# porseman 2
porseman_train2:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman-train2

porseman_dev2:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman-dev2

porseman_test2:
  _target_: dpr.data.retriever_data.JsonlQASrc
  file: data.porseman-test2

# porseman 2 pos (test is: porseman_test2)
porseman_train2_pos:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: data.porseman-train2_pos

porseman_dev2_pos:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: data.porseman-dev2_pos

# trivia (no test1)
trivia_train_1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trivia-train-1

trivia_train_40:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trivia-train-40

trivia_train_79:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train-79

trivia_dev_1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trivia-dev-1