# @package _group_

# porseman 1 (mozafari)
porseman_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman-train

porseman_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman-dev

porseman_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.porseman-test

# porseman 2
porseman2_train_binary:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman2_train_binary

porseman2_dev_binary:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.porseman2_dev_binary

porseman2_test:
  _target_: dpr.data.retriever_data.JsonlQASrc
  file: data.porseman2_test

porseman2_train_graded:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: data.porseman2_train_graded

porseman2_dev_graded:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: data.porseman2_dev_graded

porseman2_ss_graded:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: /content/drive/MyDrive/IR_Datasets/Porseman2/questions_pos_ss.jsonl

# trivia (no test1)
trivia_train_1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trivia-train-1

trivia_train_40:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trivia-train-40

trivia_train_79:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train-79

trivia_dev_1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trivia-dev-1

# trec dl
trec_train_graded:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: data.trec_train_graded

trec_dev_graded:
  _target_: dpr.data.biencoder_data.JsonGradedQADataset
  file: data.trec_dev_graded

trec_train_binary:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trec_train_binary

trec_dev_binary:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.trec_dev_binary

trec_test:
  _target_: dpr.data.retriever_data.JsonlQASrc
  file: data.trec_test

# trec dl binary
binary_trec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.binary_trec_train

binary_trec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.binary_trec_dev

binary_trec_test:
  _target_: dpr.data.retriever_data.JsonlQASrc
  file: data.binary_trec_test

# C50
c50_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.c50_train

c50_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.c50_dev

c50_test:
  _target_: dpr.data.retriever_data.JsonlQASrc
  file: data.c50_test
